version: '3.8'

services:
  postgres_container:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: app_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app_container:
    build:
      context: .
    container_name: app_container
    depends_on:
      - postgres_container
    environment:
      DB_HOST: postgres_container
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: app_db
    ports:
      - "8080:8080"

volumes:
  pg_data: